# Foundry Configuration File

[profile.default]

auto_detect_solc = false
optimizer_runs = 10_000
gas_reports_ignore = ["Counter2"]

[rpc_endpoints]

kaia = "${KAIA_RPC_URL}"
kairos = "${KAIROS_RPC_URL}"


[etherscan]


sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }
